global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pre911'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pulsepoint_ingestor'
    metrics_path: '/pulsepoint/metrics'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'nhtsa_ingestor'
    metrics_path: '/nhtsa/metrics'
    static_configs:
      - targets: ['localhost:9092']
